version: "3.7"
services:
    postgres:
        image: postgres:latest
        environment:
          POSTGRES_DB: "postgres"
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "postgres"
        ports:
          - "5440:5432"
        volumes: 
          - ./postgres-data:/var/lib/postgresql/data
            # copy the sql script to create tables
          - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql